### PR TITLE
[WIP] Clique rpc api

### PR DESCRIPTION
**Pull request by samparsky**
This is a massive work in progress for issue #35, a number of changes are currently being made

### CODE REVIEW

**Comment by 5chdn** [comment]
Are you still working on this?

**Comment by samparsky** [comment]
@5chdn Yeah will work on finishing it up this coming week

**Comment by jwasinger** [comment]
Thanks @samparsky .  This is a great help to the parity goerli implementation!

**Comment by 5chdn** [comment]
Hi @samparsky - unfortunately, I have to reject your submission. The bounty expired 16 days ago and after my ping last week you did not push any further code. I hope this does not cause any inconveniences for you and I also hope you understand that we have to move on from here. Therefore, we will hand over this task to @jleni who signalled interest in taking on the Clique RPCs this week.

**Comment by Adrenaline1554** [comment]
#35

**Comment by Adrenaline1554** [comment]
https://codesandbox.io/s/yvl79qj5vj

**Pull request closed without merging**
