### PR TITLE
prevent SystemTime panics 

### PR DESCRIPTION
**Pull request by niklasad1**
blocked on #69

### CODE REVIEW

**Comment by soc1c** [comment]
let's wait till your upstream PR is merged, otherwise, this might get messy.

once merged, you can do something like #57, resolve conflicts, and add your SystemTime panic fix.

**Comment by niklasad1** [comment]
Yeah, I just wanted to you guys to see it and shout if something looks terrible :smile:

**Comment by soc1c** [comment]
upstream PR is merged, can you update this now? @niklasad1

**Comment by niklasad1** [comment]
Cool, yes I will take of it today

**Pull request merged**
